import type { Metadata } from 'next';
import { Inter, Bungee } from 'next/font/google';

import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import { dark } from '@clerk/themes';

const inter = Inter({ subsets: ['latin'] });
const bungee = Bungee({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-bungee',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        layout: {
          socialButtonsVariant: 'iconButton',
        },
        baseTheme: dark,
      }}
    >
      <html lang='en'>
        <body className={`${inter.className} ${bungee.variable}`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
